### ISSUE TITLE
Can't lanuch hunterpie

### ISSUE THREAD

**Issue by arika163** [Haato3o/HunterPie#172]
The firewall has been closed, administrator rights have been obtained, and the path has been modified. It still prompts that the game version (421471) has not mapped.
My hunterpie version is 1.0.5,I think it's the latest version I can find.
I can't find out reason,could you please give me some advice?

By the way,it takes a long time for my computer to lanuch hunterpie,after double click the hunterpie.exe, I need wait about 5min for hunterpie window to display,maybe there is something wrong with my network?

**Comment by Haato3o** [comment]
> It still prompts that the game version (421471) has not mapped.

That means your HunterPie isn't being able to update itself, you can try manually downloading the address map file and throwing it into your `address` folder (the file can be found [here](https://github.com/Haato3o/HunterPie/blob/master/HunterPie/address/MonsterHunterWorld.421470.map)).

> By the way,it takes a long time for my computer to lanuch hunterpie,after double click the hunterpie.exe, I need wait about 5min for hunterpie window to display,maybe there is something wrong with my network?

That's also not normal, could be either your internet, firewall or even GFW if you live in China, which would also explain why it didn't update itself, as that also requires a connection to the server that hosts its files.

**Comment by intspt** [comment]
网的问题，我现在是先开Proxifier，然后再启动HunterPie就行，让HunterPie走代理，能秒开

**Comment by WorldSEnder** [comment]
I had a similar issue, although launching took only 6 seconds.

HunterPie will report "Auto-Update is disabled. If your HunterPie has any issues or doesn't support the current game version, try enabling auto-update." even if auto updating is enabled, if it fails to connect to the update server.

In my case, this was caused by a **Windows 7** configuration not explicitly enabling TLS 1.2 support. For details on how to enable this, see [the MS support article](https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392#easy), scroll down to the Easy Fix section after you made sure you have the latest windows updates.

After fixing this, everything runs just fine.

---
For discoverability:

I also assume that if the updates don't work, plugins won't show up either. So open up HunterPie and switch to the plugins tab, wait 10 seconds or so, then switch back to the console tab if no plugins loaded an error should get printed along the lines of
```
[03:36:21] System.Net.Http.HttpRequestException: [details omitted]
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of internal stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HunterPie.Plugins.PluginRegistryService.<IsRegistryAccessible>d__10.MoveNext()
```
